Debug: True

paths:
 checkpoint_path: "/home/benoit_tremblay_23/training/ef3_wl7"  # Path to the output directory.
 checkpoint_file_name: 'best_model'  # Filename to load checkpoint.
 aia_csv: '/mnt/disks/aia-raw-6h/aia-linear-6hr-aiapy/matches/matches_256_limb.csv'  # Path to the CSV with the AIA image stack paths.
 eve_norm: '/mnt/disks/aia_data/converted_data_8_channels/eve_normalization.npy'  # Path to the EVE normalization.
 eve_wl: '/mnt/disks/aia_data/converted_data_8_channels/eve_wl_names.npy'  # Path to the EVE norm.
 eve_npy: '/mnt/disks/aia_data/converted_data_8_channels/eve_converted.npy'  # Path to converted EVE data.

config:
 # AIA: [[0, 1, 2, 3, 4, 5, 6, 7]] 
 # EUVI: [[2, 3, 4, 5]]
 # EUI: [[2, 5]]
 # SUVI: [[0, 1, 2, 3, 4, 5]]
 #  
 aia_wl: [[7]]  # Wavelengths used as input [0:94, 1:131, 2:171, 3:193, 4:211, 5:304, 6:335, 7:1600].
 ions: [[0]]
 ln_model: [True]  # Use a linear model or not.
 ln_epochs: [100]  # Total number of epochs to perform during the linear model training.
 ln_lr: [1.e-2]  # Learning rate used to train the linear model.
 cnn_model: ["resnet"]  # CNN architecture to adapt: resnet or efficientnet. #'efficientnet_b3'
 cnn_lr: [1.e-4]  # Learning rate used to train the CNN model.
 cnn_dp: [0.75]  # Dropout rate used to train the CNN model.
 hybrid_loop: [True]  # Use a linear model or not.
 cnn_epochs: [100]  # Total number of epochs to perform during the CNN model training.
 epochs: [250]  # Total number of epochs to perform during training.
 lr: [1.e-4]  # Learning rate used for training
 seed: [3110]  # Seed used for the training.
 val_months: [[2, 3]] # [[2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [11, 12]]  # Month used for validation.
 test_months: [[11, 12]] # [[2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [11, 12]]  # Month used for testing.
 holdout_months: [[1, 10]]  # Month used for holdout.


wandb_init:
 entity: '4pi-euv'  # Name of wandb entity.
 project: 'irradiance-paper'  # Name of wandb project.
 group: 'instruments'  # Name of wandb group.
 job_type: 'Training'  # Nme of wandb job_type
 tags: ['development'] # Run tags
 name: 'ef3_wl7'  # Name of wandb run.
 notes: "Training for different combination of wavelengths corresponding to EUV-observing instruments."
