services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DATA_BACKEND=local
      - LOCAL_DATA_ROOT=/data
    volumes:
      - /Users/wfawcett/Documents/trillium/code/2023-FDL-X-ARD-EVE/web_app/DATA_TEST
      - ./cache:/app/cache
